"""Initial schema

Revision ID: a0c5f6e69ada
Revises: 
Create Date: 2025-04-17 18:58:44.679802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0c5f6e69ada'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_table',
    sa.Column('cache_id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=100), nullable=False),
    sa.Column('cache_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cache_id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_index('ix_cache_table_cache_key', 'cache_table', ['cache_key'], unique=False)
    op.create_table('metrics',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_index('ix_metrics_metric_name', 'metrics', ['metric_name'], unique=False)
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('permission_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('permission_name')
    )
    op.create_index('ix_permissions_permission_name', 'permissions', ['permission_name'], unique=False)
    op.create_table('process_tracking',
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('process_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('process_id')
    )
    op.create_index('ix_process_tracking_process_name', 'process_tracking', ['process_name'], unique=False)
    op.create_index('ix_process_tracking_status', 'process_tracking', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_index('ix_roles_role_name', 'roles', ['role_name'], unique=False)
    op.create_table('tenants',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('tenant_name', sa.String(length=100), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id'),
    sa.UniqueConstraint('tenant_name')
    )
    op.create_index('ix_tenants_tenant_name', 'tenants', ['tenant_name'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('data_sources',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('source_id'),
    sa.UniqueConstraint('source_name')
    )
    op.create_index('ix_data_sources_source_name', 'data_sources', ['source_name'], unique=False)
    op.create_index('ix_data_sources_tenant_id', 'data_sources', ['tenant_id'], unique=False)
    op.create_table('encrypted_secrets',
    sa.Column('secret_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('secret_key', sa.String(length=100), nullable=False),
    sa.Column('secret_value', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('secret_id')
    )
    op.create_index('ix_encrypted_secrets_tenant_id', 'encrypted_secrets', ['tenant_id'], unique=False)
    op.create_table('logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_logs_user_id', 'logs', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_index('ix_role_permission_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_index('ix_role_permission_role_id', 'role_permissions', ['role_id'], unique=False)
    op.create_table('tenant_user',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id')
    )
    op.create_index('ix_tenant_user_tenant_id', 'tenant_user', ['tenant_id'], unique=False)
    op.create_index('ix_tenant_user_user_id', 'tenant_user', ['user_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index('ix_user_role_role_id', 'user_role', ['role_id'], unique=False)
    op.create_index('ix_user_role_user_id', 'user_role', ['user_id'], unique=False)
    op.create_table('datasets',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('dataset_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('dataset_id'),
    sa.UniqueConstraint('dataset_name')
    )
    op.create_index('ix_datasets_source_id', 'datasets', ['source_id'], unique=False)
    op.create_index('ix_datasets_tenant_id', 'datasets', ['tenant_id'], unique=False)
    op.create_table('time_series_metadata',
    sa.Column('timeseries_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('timeseries_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.source_id'], ),
    sa.PrimaryKeyConstraint('timeseries_id')
    )
    op.create_index('ix_time_series_metadata_source_id', 'time_series_metadata', ['source_id'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.String(length=50), nullable=False),
    sa.Column('preprocessing_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('storage_location', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.dataset_id'], ),
    sa.PrimaryKeyConstraint('dataset_version_id')
    )
    op.create_index('ix_dataset_versions_dataset_id', 'dataset_versions', ['dataset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dataset_versions_dataset_id', table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index('ix_time_series_metadata_source_id', table_name='time_series_metadata')
    op.drop_table('time_series_metadata')
    op.drop_index('ix_datasets_tenant_id', table_name='datasets')
    op.drop_index('ix_datasets_source_id', table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('ix_user_role_user_id', table_name='user_role')
    op.drop_index('ix_user_role_role_id', table_name='user_role')
    op.drop_table('user_role')
    op.drop_index('ix_tenant_user_user_id', table_name='tenant_user')
    op.drop_index('ix_tenant_user_tenant_id', table_name='tenant_user')
    op.drop_table('tenant_user')
    op.drop_index('ix_role_permission_role_id', table_name='role_permissions')
    op.drop_index('ix_role_permission_permission_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_logs_user_id', table_name='logs')
    op.drop_table('logs')
    op.drop_index('ix_encrypted_secrets_tenant_id', table_name='encrypted_secrets')
    op.drop_table('encrypted_secrets')
    op.drop_index('ix_data_sources_tenant_id', table_name='data_sources')
    op.drop_index('ix_data_sources_source_name', table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_tenants_tenant_name', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('ix_roles_role_name', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_process_tracking_status', table_name='process_tracking')
    op.drop_index('ix_process_tracking_process_name', table_name='process_tracking')
    op.drop_table('process_tracking')
    op.drop_index('ix_permissions_permission_name', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('ix_metrics_metric_name', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index('ix_cache_table_cache_key', table_name='cache_table')
    op.drop_table('cache_table')
    # ### end Alembic commands ###
