"""update tables

Revision ID: 03d4a5660a75
Revises: ac7fd653224b
Create Date: 2025-04-21 22:12:20.997015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d4a5660a75'
down_revision: Union[str, None] = 'ac7fd653224b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('created_by', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'created_by')
    # ### end Alembic commands ###
